# Generated by Django 5.1.1 on 2024-10-14 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FichaMedica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('provincia', models.CharField(max_length=100)),
                ('cum', models.CharField(max_length=20)),
                ('fecha_nacimiento', models.DateField()),
                ('grupo', models.CharField(max_length=10)),
                ('seccion', models.CharField(max_length=50)),
                ('alerta', models.CharField(max_length=100)),
            ],
        ),
    ]
